TEAM_NUMBER = 30

COMMAND_LENGTH = 14

SELECT_MODE = 0
STRIDE_LEFT_LEG = 1
STRIDE_RIGHT_LEG = 2
SPEED = 3
SWING_LEFT_LEG = 4
SWING_RIGHT_LEG = 5
UP_LEFT_LEG = 6
UP_RIGHT_LEG = 7
TURN_LEFT_ANGLE = 8
TURN_RIGHT_ANGLE = 9
OFFSET_LEFT_LEG = 10
OFFSET_RIGHT_LEG = 11
HEAD_LEFT_RIGHT = 12
HEAD_UP_DOWN = 13